// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcehhaycvwveezrbmbst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjZWhoYXljdnd2ZWV6cmJtYnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyMzI0MzksImV4cCI6MjA1ODgwODQzOX0.pNlEJsi4T2rbzSN1CqY9hMtVRG8zE7SZvD07yG2j2NY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);